# Generated by Django 4.2.16 on 2024-10-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
