# Generated by Django 4.2.16 on 2024-10-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0003_answer_question_delete_user_answer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.TextField(blank=True, help_text='הפרידי בין האפשרויות באמצעות פסיק', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'טקסט חופשי'), ('multiple_choice', 'בחירה מרובה')], default='text', max_length=50),
        ),
    ]
